#ifndef RB_RUNTIME_H
#define RB_RUNTIME_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── String type (refcounted) ─────────────────────────── */

typedef struct rb_string {
    int32_t refcount;
    int32_t length;
    char data[];  /* flexible array member */
} rb_string_t;

rb_string_t* rb_string_alloc(const char* cstr);
rb_string_t* rb_string_concat(rb_string_t* a, rb_string_t* b);
int32_t rb_string_compare(rb_string_t* a, rb_string_t* b);
void rb_string_retain(rb_string_t* s);
void rb_string_release(rb_string_t* s);

/* ── Print ────────────────────────────────────────────── */

void rb_print_int(int32_t value);
void rb_print_float(float value);
void rb_print_string(rb_string_t* s);
void rb_print_newline(void);

/* ── Input ────────────────────────────────────────────── */

int32_t rb_input_int(const char* prompt);
float rb_input_float(const char* prompt);
rb_string_t* rb_input_string(const char* prompt);

/* ── Panic ────────────────────────────────────────────── */

void rb_panic(const char* message) __attribute__((noreturn));

/* ── GPIO ─────────────────────────────────────────────── */

void rb_gpio_mode(int32_t pin, int32_t mode);
void rb_gpio_set(int32_t pin, int32_t value);
int32_t rb_gpio_read(int32_t pin);

/* ── Delay ────────────────────────────────────────────── */

void rb_delay(int32_t ms);

/* ── I2C ──────────────────────────────────────────────── */

void rb_i2c_setup(int32_t bus, int32_t sda, int32_t scl, int32_t freq);
void rb_i2c_write(int32_t addr, int32_t data);
int32_t rb_i2c_read(int32_t addr, int32_t length);

/* ── SPI ──────────────────────────────────────────────── */

void rb_spi_setup(int32_t bus, int32_t clk, int32_t mosi, int32_t miso, int32_t freq);
int32_t rb_spi_transfer(int32_t data);

/* ── WiFi ─────────────────────────────────────────────── */

void rb_wifi_connect(rb_string_t* ssid, rb_string_t* password);
int32_t rb_wifi_status(void);
void rb_wifi_disconnect(void);

/* ── Arrays ───────────────────────────────────────────── */

void rb_array_check_dim_size(int32_t dim_value, int32_t dim_index);
void* rb_array_alloc(int32_t element_size, int32_t total_elements);
void rb_array_free(void* ptr);
void rb_array_bounds_check(int32_t index, int32_t size);

/* ── Entry point (generated by compiler) ──────────────── */

extern void basic_program_entry(void);

#ifdef __cplusplus
}
#endif

#endif /* RB_RUNTIME_H */
